### PR TITLE
Message style improvements

### PR DESCRIPTION
**Pull request by alilleybrinker**

### CODE REVIEW

**Review by cstepanian — DISMISSED** [review]

**Comment by alilleybrinker** [comment]
Looks like the failing check is due to a failed property-based test in `pact_verifier_cli`, which we're not touching, so I'm inclined to override it, although it looks like there are also changes missing from the `pact_matching_ffi` branch that would block merging, so I'll need to fix that first.

**Comment by alilleybrinker** [comment]
Rebased on the latest from the `pact_matching_ffi` branch, and pushed again. It'll rerun the checks, and the property-based test (which is probabilistic) might fail again, and is irrelevant. I'll let it finish just to make sure the rebase didn't break anything, but if it blocks on the same issue I'll override it.

**Comment by alilleybrinker** [comment]
Ah, looks like the rebase also means it needs a new approval from @cstepanian.

**Review by cstepanian — APPROVED** [review]

**Comment by alilleybrinker** [comment]
*sigh*, yeah, that test failed again. It's frustrating that upstream doesn't rigorously require their own commits to pass CI (it seems) because 1) it breaks our builds, and 2) it seems to periodically add a number of warnings, as we discussed yesterday. At any rate, I'm going to temporarily turn off the requirement that checks pass, merge this, and then turn the requirement back on.

**Pull request merged**
